sudo: false
language: node_js
matrix:
  include:
  - node_js: 5.9 # Latest stable
  - node_js: 4.4 # LTS
  - node_js: 0.10 # Minimum supported
script:
- npm test
cache:
  directories:
  - $HOME/.npm

